export { lock } from './components/lock';
export { pencil } from './components/pencil';
export { instagram } from './components/instagram';
export { youtube } from './components/youtube';
export { mail } from './components/mail';
export { faceBook } from './components/faceBook';
export { tikTok } from './components/tikTok';
export { telegram } from './components/telegram';
export { gitHub } from './components/gitHub';
